# Generated by Django 4.1.1 on 2023-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_id', models.CharField(max_length=10)),
                ('num_code', models.CharField(max_length=3)),
                ('char_code', models.CharField(max_length=5)),
                ('nominal', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('previous', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
